site_name: MkDocs Demo Site
repo_name: fotrimzi/mkdocs
repo_url: https://github.com/fotrimzi/mkdocs/
edit_uri: edit/master/docs/
site_description: MkDocs demo/test site and feature exploration
site_author: Paul Jacobs

theme:
  name: material
  custom_dir: theme
  navigation_depth: 2
  features:
    - tabs
  palette:
    scheme: default
    primary: red
    accent: indigo

extra_css:
  - css/extra.css

use_directory_urls: false

markdown_extensions:
    - toc:
        permalink: True
        permalink_title: Link to this section
        anchorlink: True
#        separator: "_"
    - admonition
    - smarty:
        smart_angled_quotes: True
    - pymdownx.smartsymbols
    - pymdownx.mark
    - pymdownx.tabbed
    - pymdownx.tilde
#    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: true
    - markdown_svgbob:
        tag_type: inline_svg
        bg_color: white
        fg_color: black
        min_char_width: 80
    - pymdownx.emoji
    - attr_list

plugins:
    - search
    - mermaid2
    - table-reader
    - exclude:
        glob:
          - _include/*
    - redirects:
        redirect_maps:
          'doesnotexist.md': 'redirects.md'
    - macros:
        include_yaml: ['extra.yml']

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

################################################################################
# NAVIGATION
################################################################################

nav:
  - Home:
    - index.md
  - Presentation:
    - admonitions.md
    - highlights.md
    - strikethrough.md
    - code-blocks.md
    - theming.md
    - images.md
    - figures.md
    - diagrams.md
    - symbols.md
    - buttons.md
  - Links:
    - git.md
    - redirects.md
    - refs-and-links.md
  - Navigation:
    - toc.md
    - toc-alt.md
  - Reuse:
    - include.md
    - exclude.md
    - tables.md
    - replacements.md
  - Export:
    - pdf.md
